global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis_exporter_1'
    static_configs:
      - targets: ['redis-exporter-1:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter-1:9121

  - job_name: 'redis_exporter_2'
    static_configs:
      - targets: ['redis-exporter-2:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter-2:9121

  - job_name: 'redis_exporter_3'
    static_configs:
      - targets: ['redis-exporter-3:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter-3:9121

  - job_name: 'twemproxy'
    static_configs:
      - targets:
        - 'twemproxy:22122'
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: twemproxy:22122
    metric_relabel_configs:
      - source_labels: [client_connections]
        target_label: twemproxy_client_connections
      - source_labels: [client_eof]
        target_label: twemproxy_client_eof
      - source_labels: [client_err]
        target_label: twemproxy_client_err
      - source_labels: [client_connections]
        target_label: twemproxy_client_connections
      - source_labels: [fragments]
        target_label: twemproxy_fragments
      - source_labels: [forward_error]
        target_label: twemproxy_forward_error
      - source_labels: [server_ejects]
        target_label: twemproxy_server_ejects

rule_files:
  - "rules.yml"