global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
#  - job_name: 'spring-actuator'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:8080']

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo_exporter:9216']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']