global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis:6379']
  - job_name: 'rabbitmq_exporter'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka:9308']