version: '3'
services:
  redis:
    image: redis:3.2
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - backend

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    ports:
      - 9121:9121
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

  rabbitmq_exporter:
    image: kbudde/rabbitmq-exporter:latest
    container_name: rabbitmq_exporter
    ports:
      - 9419:9419
    environment:
      - RABBIT_URL=http://rabbitmq:15672
    networks:
      - backend

  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper/zoo.cfg:/conf/zoo.cfg
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:3.3.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    volumes:
      - ./kafka/server.properties:/etc/kafka/server.properties
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  kafka_exporter:
    image: danielqsj/kafka-exporter:v1.2.0
    container_name: kafka_exporter
    ports:
      - 9308:9308
    environment:
      KAFKA_SERVER: kafka:9092
    networks:
      - backend

  mongo:
    image: mongo:3.4
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongod.conf:/etc/mongo/mongod.conf
      - mongo_data:/data/db
    command: mongod --config /etc/mongo/mongod.conf
    networks:
      - backend

  mongo_exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongo_exporter
    ports:
      - 9216:9216
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend

  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - backend

volumes:
  redis_data:
  rabbitmq_data:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:
  mongo_data:

networks:
  backend: